; =============================================================================
; Generated by m3 compiler from examples/game.m3
; Package: main
; =============================================================================

.zp
_frame_counter:
  .res 1
_player_x:
  .res 1
_player_y:
  .res 1

.ram
_enemies:
  .res 1

.wram
_high_score:
  .res 1

; Constants and ROM Data
.export _PPU_CTRL
_PPU_CTRL:
  .word $2000

.export _PPU_MASK
_PPU_MASK:
  .word $2001

.export _PPU_STAT
_PPU_STAT:
  .word $2002

_enemy_spawn_x:
  .byte $10, $30, $50, $70, $90, $B0, $D0, $F0

; Functions
.proc _init_enemies
  RTS
.endproc

.proc _update_enemies
  RTS
.endproc

.bank 0
.proc _main
  ; Inline assembly
          :   BIT $2002
              BPL :-
  RTS
.endproc

