; =============================================================================
; Generated by m3 compiler from game/src/main.m3
; Package: main
; =============================================================================

; Imports
; import "memory.m3"
; import "mmc.m3"
; import "ppu.m3"
; import "ppu_driver.m3"
; import "./data/data.m3"

; Compile-time Definitions
.define _mmc_MMC3_BANK_SELECT $8000

.define _mmc_MMC3_BANK_DATA $8001

.define _mmc_MMC3_MIRRORING $A000

.define _mmc_MMC3_WRAM_PROT $A001

.define _mmc_MMC3_IRQ_LATCH $C000

.define _mmc_MMC3_IRQ_RELOAD $C001

.define _mmc_MMC3_IRQ_DISABLE $E000

.define _mmc_MMC3_IRQ_ENABLE $E001

.define _ppu_PPU_CTRL $2000

.define _ppu_PPU_MASK $2001

.define _ppu_PPU_STATUS $2002

.define _ppu_OAM_ADDR $2003

.define _ppu_OAM_DATA $2004

.define _ppu_PPU_SCROLL $2005

.define _ppu_PPU_ADDR $2006

.define _ppu_PPU_DATA $2007

.define _ppu_driver_PPU_CTRL $2000

.define _ppu_driver_PPU_MASK $2001

.define _ppu_driver_PPU_STATUS $2002

.define _ppu_driver_PPU_SCROLL $2005

.define _ppu_driver_PPU_ADDR $2006

.define _ppu_driver_PPU_DATA $2007

.define _ppu_driver_CMD_END $00

.define _ppu_driver_CMD_HORIZ $01

.define _ppu_driver_CMD_VERT $02

.define _ppu_driver_CMD_BYTE $03

.ram
_main_paletteMirror:
  .res 32

; Functions
.bank 63
.code
.proc _main_main
  JSR _ppu_Disable
  LDA #^_data_TilesPal
  JSR _mmc_PushDataBank
  LDA #<_main_paletteMirror
  STA __leaf_param0
  LDA #>_main_paletteMirror
  STA __leaf_param0+1
  LDA #$10
  STA __leaf_param2
  LDA #$00
  STA __leaf_param2+1
  LDA #<_data_TilesPal_0
  LDX #>_data_TilesPal_0
  JSR _memory_Copy
  LDA #<(_main_paletteMirror + 16)
  STA __leaf_param0
  LDA #>(_main_paletteMirror + 16)
  STA __leaf_param0+1
  LDA #$10
  STA __leaf_param2
  LDA #$00
  STA __leaf_param2+1
  LDA #<0
  LDX #>0
  JSR _memory_Copy
  JSR _mmc_PopDataBank
  LDA #<_main_paletteMirror
  LDX #>_main_paletteMirror
  JSR _ppu_DirectUploadPalette
  LDA #^_data_TilesChr
  JSR _mmc_PushDataBank
  LDA #$00
  STA __leaf_param0
  LDA #$00
  STA __leaf_param0+1
  LDA #$00
  STA __leaf_param2
  LDA #$08
  STA __leaf_param2+1
  LDA #<_data_TilesChr_0
  LDX #>_data_TilesChr_0
  JSR _ppu_DirectUpload
  LDA #$00
  STA __leaf_param0
  LDA #$08
  STA __leaf_param0+1
  LDA #$00
  STA __leaf_param2
  LDA #$08
  STA __leaf_param2+1
  LDA #<_data_TilesChr_1
  LDX #>_data_TilesChr_1
  JSR _ppu_DirectUpload
  JSR _mmc_PopDataBank
  LDA #^_data_SpritesChr
  JSR _mmc_PushDataBank
  LDA #$00
  STA __leaf_param0
  LDA #$10
  STA __leaf_param0+1
  LDA #$00
  STA __leaf_param2
  LDA #$04
  STA __leaf_param2+1
  LDA #<_data_SpritesChr_0
  LDX #>_data_SpritesChr_0
  JSR _ppu_DirectUpload
  JSR _mmc_PopDataBank
  JSR _ppu_Enable
  JSR _ppu_driver_Clear
@for_head_1:
  JSR _ppu_WaitForVBlank
@for_post_2:
  JMP @for_head_1
@for_exit_3:
  RTS
.endproc

.bank 63
.code
.proc _main_nmi
  JSR _ppu_driver_Process
  RTS
.endproc

