package compiler

import (
	"fmt"
	"os"
	"strings"
)

// Compile parses an m3 source string into an AST and generates the assembly output.
func Compile(filename, source string) (*SourceFile, string, error) {
	lexer := NewLexer(filename, source)
	parser := NewParser(lexer)

	astFile, err := parser.ParseSourceFile()
	if err != nil {
		return nil, "", err
	}

	asmCode, err := generateAssembly(astFile)
	if err != nil {
		return astFile, "", err
	}

	return astFile, asmCode, nil
}

// CompileFile reads an input .m3 file, compiles it, and writes the assembly output to outputFile.
func CompileFile(inputFile, outputFile string) error {
	content, err := os.ReadFile(inputFile)
	if err != nil {
		return fmt.Errorf("failed to read source file %q: %w", inputFile, err)
	}

	_, asmCode, err := Compile(inputFile, string(content))
	if err != nil {
		return err
	}

	if err := os.WriteFile(outputFile, []byte(asmCode), 0644); err != nil {
		return fmt.Errorf("failed to write assembly file %q: %w", outputFile, err)
	}

	return nil
}

// generateAssembly generates assembly source from the AST.
func generateAssembly(file *SourceFile) (string, error) {
	var sb strings.Builder

	sb.WriteString("; =============================================================================\n")
	sb.WriteString(fmt.Sprintf("; Generated by m3 compiler from %s\n", file.Pos().Filename))
	if file.PackageName != "" {
		sb.WriteString(fmt.Sprintf("; Package: %s\n", file.PackageName))
	}
	sb.WriteString("; =============================================================================\n\n")

	// Imports
	if len(file.Imports) > 0 {
		sb.WriteString("; Imports\n")
		for _, imp := range file.Imports {
			sb.WriteString(fmt.Sprintf("; import %q\n", imp.Path))
		}
		sb.WriteString("\n")
	}

	// Group declarations by category
	var zpVars []*VarDecl
	var ramVars []*VarDecl
	var wramVars []*VarDecl
	var defineDecls []*DefineDecl
	var constDecls []*ConstDecl
	var funcDecls []*FuncDecl

	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *VarDecl:
			switch d.Storage {
			case StorageZP:
				zpVars = append(zpVars, d)
			case StorageWRAM:
				wramVars = append(wramVars, d)
			default:
				ramVars = append(ramVars, d)
			}
		case *DefineDecl:
			defineDecls = append(defineDecls, d)
		case *ConstDecl:
			constDecls = append(constDecls, d)
		case *FuncDecl:
			funcDecls = append(funcDecls, d)
		}
	}

	// Compile-time Definitions (.define)
	if len(defineDecls) > 0 {
		sb.WriteString("; Compile-time Definitions\n")
		for _, d := range defineDecls {
			name := mangleSymbol(d.Name)
			if isExported(d.Name) {
				sb.WriteString(fmt.Sprintf(".export %s\n", name))
			}
			sb.WriteString(fmt.Sprintf(".define %s %s\n\n", name, formatConstExpr(d.Value)))
		}
	}

	// Zero page segment
	if len(zpVars) > 0 {
		sb.WriteString(".zp\n")
		for _, v := range zpVars {
			name := mangleSymbol(v.Name)
			if isExported(v.Name) {
				sb.WriteString(fmt.Sprintf(".export %s\n", name))
			}
			sb.WriteString(fmt.Sprintf("%s:\n", name))
			sb.WriteString("  .res 1\n")
		}
		sb.WriteString("\n")
	}

	// RAM segment
	if len(ramVars) > 0 {
		sb.WriteString(".ram\n")
		for _, v := range ramVars {
			name := mangleSymbol(v.Name)
			if isExported(v.Name) {
				sb.WriteString(fmt.Sprintf(".export %s\n", name))
			}
			sb.WriteString(fmt.Sprintf("%s:\n", name))
			sb.WriteString("  .res 1\n")
		}
		sb.WriteString("\n")
	}

	// WRAM segment
	if len(wramVars) > 0 {
		sb.WriteString(".wram\n")
		for _, v := range wramVars {
			name := mangleSymbol(v.Name)
			if isExported(v.Name) {
				sb.WriteString(fmt.Sprintf(".export %s\n", name))
			}
			sb.WriteString(fmt.Sprintf("%s:\n", name))
			sb.WriteString("  .res 1\n")
		}
		sb.WriteString("\n")
	}

	// Constants / PRG-ROM
	if len(constDecls) > 0 {
		sb.WriteString("; Constants and ROM Data\n")
		for _, c := range constDecls {
			if c.Bank != nil {
				if c.Bank.IsAuto {
					sb.WriteString(".bank auto\n")
				} else if num, ok := c.Bank.Value.(*NumberLit); ok {
					sb.WriteString(fmt.Sprintf(".bank %d\n", num.Value))
				}
			}
			name := mangleSymbol(c.Name)
			if isExported(c.Name) {
				sb.WriteString(fmt.Sprintf(".export %s\n", name))
			}
			sb.WriteString(fmt.Sprintf("%s:\n", name))
			if strLit, ok := c.Value.(*StringLit); ok {
				sb.WriteString(fmt.Sprintf("  .asciiz %q\n", strLit.Value))
			} else if arrLit, ok := c.Value.(*ArrayLit); ok {
				var items []string
				for _, elem := range arrLit.Elements {
					if n, ok := elem.(*NumberLit); ok {
						items = append(items, fmt.Sprintf("$%02X", n.Value&0xFF))
					} else {
						items = append(items, "0")
					}
				}
				if len(items) > 0 {
					sb.WriteString(fmt.Sprintf("  .byte %s\n", strings.Join(items, ", ")))
				}
			} else if numLit, ok := c.Value.(*NumberLit); ok {
				sb.WriteString(fmt.Sprintf("  .word $%04X\n", numLit.Value))
			}
			sb.WriteString("\n")
		}
	}

	// Functions / Procedures
	if len(funcDecls) > 0 {
		sb.WriteString("; Functions\n")
		for _, f := range funcDecls {
			if f.Bank != nil {
				if f.Bank.IsAuto {
					sb.WriteString(".bank auto\n")
				} else if num, ok := f.Bank.Value.(*NumberLit); ok {
					sb.WriteString(fmt.Sprintf(".bank %d\n", num.Value))
				}
			}

			name := mangleSymbol(f.Name)
			if isExported(f.Name) {
				sb.WriteString(fmt.Sprintf(".export %s\n", name))
			}
			sb.WriteString(fmt.Sprintf(".proc %s\n", name))

			// Emit any inline assembly inside the function
			if f.Body != nil {
				emitBodyStmts(&sb, f.Body.Stmts)
			}

			sb.WriteString("  RTS\n")
			sb.WriteString(".endproc\n\n")
		}
	}

	return sb.String(), nil
}

func emitBodyStmts(sb *strings.Builder, stmts []Stmt) {
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *AsmStmt:
			sb.WriteString("  ; Inline assembly\n")
			lines := strings.Split(s.Body, "\n")
			for _, line := range lines {
				trimmed := strings.TrimRight(line, " \t\r")
				if trimmed != "" {
					sb.WriteString(fmt.Sprintf("  %s\n", trimmed))
				}
			}
		case *BlockStmt:
			emitBodyStmts(sb, s.Stmts)
		case *IfStmt:
			if s.Then != nil {
				emitBodyStmts(sb, s.Then.Stmts)
			}
			if s.Else != nil {
				if elseBlock, ok := s.Else.(*BlockStmt); ok {
					emitBodyStmts(sb, elseBlock.Stmts)
				}
			}
		case *ForStmt:
			if s.Body != nil {
				emitBodyStmts(sb, s.Body.Stmts)
			}
		}
	}
}

func mangleSymbol(name string) string {
	return "_" + name
}

func isExported(name string) bool {
	if len(name) == 0 {
		return false
	}
	first := name[0]
	return first >= 'A' && first <= 'Z'
}

func formatConstExpr(expr Expr) string {
	if expr == nil {
		return "0"
	}
	switch e := expr.(type) {
	case *NumberLit:
		if e.Raw != "" {
			if strings.HasPrefix(e.Raw, "0x") || strings.HasPrefix(e.Raw, "0X") {
				return "$" + e.Raw[2:]
			}
			if strings.HasPrefix(e.Raw, "0b") || strings.HasPrefix(e.Raw, "0B") {
				return "%" + e.Raw[2:]
			}
			return e.Raw
		}
		return fmt.Sprintf("%d", e.Value)
	case *CharLit:
		return fmt.Sprintf("'%c'", e.Value)
	case *BoolLit:
		if e.Value {
			return "1"
		}
		return "0"
	case *StringLit:
		return fmt.Sprintf("%q", e.Value)
	case *Ident:
		return mangleSymbol(e.Name)
	case *ParenExpr:
		return fmt.Sprintf("(%s)", formatConstExpr(e.Expr))
	case *UnaryExpr:
		opStr := e.Op.String()
		switch e.Op {
		case TokenTilde, TokenCaret:
			opStr = "~"
		case TokenBang:
			opStr = "!"
		case TokenLt:
			opStr = "<"
		case TokenGt:
			opStr = ">"
		case TokenAmp:
			opStr = "^"
		}
		return opStr + formatConstExpr(e.Operand)
	case *BinaryExpr:
		opStr := e.Op.String()
		switch e.Op {
		case TokenEqEq:
			opStr = "=="
		case TokenBangEq:
			opStr = "!="
		}
		return fmt.Sprintf("%s %s %s", formatConstExpr(e.Left), opStr, formatConstExpr(e.Right))
	case *CallExpr:
		if len(e.Args) == 1 {
			return formatConstExpr(e.Args[0])
		}
		return "0"
	default:
		return "0"
	}
}
